# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

#  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first 

# The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here
#  Then change `bindd` to `unbind`

# E.g. 
# unbind = $mainMod, Return, Open terminal, exec, $term
# bindd = $mainMod, Return, Open terminal, exec, ghostty 
#
# unbind = $mainMod, E, file manager, exec, $files
# bindd = $mainMod, T, file manager, exec, $files

# If you are ADDING a bindd, make sure you include the description 
# Other the keybind search menu might not show it properly 

# E.g.
# bindd = $mainMod, Z, My z app, exec APPNAME

# ================================ variables =======================
$browser = google-chrome-stable

# ================================ unbinds =========================
unbind = $mainMod, W
unbind = $mainMod Shift, W
unbind = $mainMod, Q
unbind = $mainMod shift, Q
unbind = $mainMod, G
unbind = $mainMod, D
unbind = $mainMod, H
# ==================================================================

# ================================ keybinds ========================
# Replacements
bindd = $mainMod, W, Close active window, killactive,
bindd = $mainMod Shift, W, Terminate active process, exec, $scriptsDir/KillActiveProcess.sh
bindd = $mainMod, Q, select wallpaper, exec, $UserScripts/WallpaperSelect.sh
bindd = $mainMod Shift, Q, wallpaper effects, exec, $UserScripts/WallpaperEffects.sh
bindd = $mainMod, Space, app launcher, exec, pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window
bindd = $mainMod Shift Ctrl, H, help / cheat sheet, exec, $scriptsDir/KeyHints.sh

# Chrome apps
bindd = $mainMod, Y, Youtube, exec, google-chrome-stable --app="https://youtube.com"
bindd = $mainMod, C, Gemini, exec, google-chrome-stable --app="https://gemini.google.com/"

# Movement
bindd = $mainMod, H, Go to left window, movefocus, l
bindd = $mainMod, J, Go to left window, movefocus, d
bindd = $mainMod, K, Go to left window, movefocus, u
bindd = $mainMod, L, Go to left window, movefocus, r

bindde = $mainMod Shift, H, Move active window to the left, exec, $moveactivewindow -30 0 || hyprctl dispatch movewindow l
bindde = $mainMod Shift, L, Move active window to the right, exec, $moveactivewindow 30 0 || hyprctl dispatch movewindow r
bindde = $mainMod Shift, K, Move active window up, exec, $moveactivewindow  0 -30 || hyprctl dispatch movewindow u
bindde = $mainMod Shift, J, Move active window down, exec, $moveactivewindow 0 30 || hyprctl dispatch movewindow d

# Apps
bindd = $mainMod, G, WhatsApp, exec, zapzap
bindd = $mainMod, D, Discord, exec, discord

# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset
