-- -- Dynamic Theme for Neovim (Omarchy Integration)
-- -- 1. Gets current theme name from 'omarchy-theme-current'
-- -- 2. Loads the specific theme file: ~/.config/omarchy/themes/[THEME]/neovim.lua
--
-- return {
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = function()
--         -- PATH CONFIGURATION
--         local bin_path = vim.env.HOME .. "/.local/share/omarchy/bin/omarchy-theme-current"
--         local theme_base_dir = vim.env.HOME .. "/.config/omarchy/themes/"
--
--         -- 1. Determine the Active Theme Name
--         local theme_name = "aetheria" -- Default fallback
--
--         -- Run the system command to get the current theme name
--         local handle = io.popen(bin_path)
--         if handle then
--           local result = handle:read("*a")
--           handle:close()
--           if result and result ~= "" then
--             -- Clean up whitespace (remove newlines)
--             theme_name = result:gsub("%s+", "")
--           end
--         end
--
--         -- 2. Construct the full path to the theme file
--         -- e.g., /home/nick/.config/omarchy/themes/aetheria/neovim.lua
--         local theme_file = theme_base_dir .. theme_name .. "/neovim.lua"
--
--         -- 3. Attempt to execute the Omarchy theme file
--         -- We use 'dofile' because the file contains immediate 'hl()' commands
--         local ok, err = pcall(dofile, theme_file)
--
--         -- 4. FALLBACK: Use static Aetheria colors if loading failed
--         if not ok then
--           -- Optional: notify user if theme file isn't found
--           -- vim.notify("Omarchy theme load failed: " .. theme_file, vim.log.levels.WARN)
--
--           local colors = {
--             hex_0e091d = "#0e091d", hex_061F23 = "#061F23", hex_092F34 = "#092F34",
--             hex_0C3F45 = "#0C3F45", hex_0F5057 = "#0F5057", hex_126069 = "#126069",
--             hex_C8E967 = "#C8E967", hex_A8D61F = "#A8D61F", hex_8CB319 = "#8CB319",
--             hex_9147a8 = "#9147a8", hex_E20342 = "#E20342", hex_FF7F41 = "#FF7F41",
--             hex_04C5F0 = "#04C5F0", hex_f93d3b = "#f93d3b", hex_ffbe74 = "#ffbe74",
--             hex_FD3E6A = "#FD3E6A", hex_7cd699 = "#7cd699", hex_47A854 = "#47A854",
--           }
--
--           vim.cmd("highlight clear")
--           if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
--           vim.o.termguicolors = true
--           vim.o.background = "dark"
--           vim.g.colors_name = "aetheria-fallback"
--
--           local hl = vim.api.nvim_set_hl
--           hl(0, "Normal", { fg = colors.hex_C8E967, bg = colors.hex_0e091d })
--           hl(0, "NormalFloat", { fg = colors.hex_C8E967, bg = colors.hex_061F23 })
--           hl(0, "Cursor", { fg = colors.hex_0e091d, bg = colors.hex_9147a8 })
--           hl(0, "LineNr", { fg = colors.hex_8CB319 })
--         end
--       end,
--     },
--   },
-- }
